title: Tobias Liaudat
description: PhD student in Signal Processing and Machine Learning applied to Astrophysics.
show_downloads: true

# baseurl: "/tobias-liaudat" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
# url: "https://tobias-liaudat.github.io" # change this to the base hostname & protocol for your site
# url: "http://localhost:4000/tobias-liaudat"
baseurl: ""
url: ""
image_path: /assets/images

google_analytics: UA-163435936-1

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
myname: Tobias Liaudat
author: Tobias Liaudat
twitter:
  username:
github:
  owner_url: https://github.com/tobias-liaudat
  owner_name: Tobias Liaudat
linkedin:
  owner_url: https://www.linkedin.com/in/tobias-liaudat/
  owner_name: Tobias Liaudat
googlescholar:
  owner_url: https://scholar.google.com/citations?user=5YLM_sEAAAAJ&hl=en&oi=ao
  owner_name: Tobias Liaudat
contact:
  contact_url: mailto:tobias.liaudat@cea.fr


plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about', 'CV', 'Publications', 'Miscellaneous']
# theme: jekyll-theme-cayman-blog
